root: true

parser: '@typescript-eslint/parser'

plugins:
  - '@typescript-eslint'
  - 'prettier'
  - 'react-hooks'
  - jest

extends:
  - 'eslint:recommended'
  - 'plugin:prettier/recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:jest/recommended'

rules:
  '@typescript-eslint/camelcase': 'off'
  '@typescript-eslint/no-unused-vars':
    - 'error'
    - varsIgnorePattern: '^_'
  'prettier/prettier': 'error'
  'react-hooks/exhaustive-deps':
    - 'error'
    - additionalHooks: useAsync
