image: node:14.17.6

stages:
  - test
  - deploy

variables:
  SENTRY_DSN: $SENTRY_DSN

lint:
  stage: test
  before_script:
    - yarn
  script:
    - yarn lint

test:
  stage: test
  before_script:
    - yarn
  script:
    - yarn test

pages:
  stage: deploy
  before_script:
    - yarn
  script:
    - yarn build
    - yarn next export
    # If we don't remove public, mv moves out into public which is not what we want
    - rm -rf public
    - mv out public
  artifacts:
    paths:
      - public
  only:
    - master
